# Generated by Django 2.0.2 on 2018-04-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSite', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20),
        ),
    ]
