# Generated by Django 2.0.2 on 2018-04-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSite', '0003_auto_20180411_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='times',
            field=models.CharField(max_length=20),
        ),
    ]
