# Generated by Django 2.0.2 on 2018-04-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseSite', '0004_auto_20180411_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseSite.Course'),
            preserve_default=False,
        ),
    ]
