# Generated by Django 2.0.2 on 2018-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSite', '0005_review_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cost',
            new_name='has_book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='difficulty',
            new_name='test_difficulty',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='workload',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='times',
            field=models.CharField(max_length=10),
        ),
    ]
