# Generated by Django 2.0.2 on 2018-04-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSite', '0009_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='attend_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='liked_teaching',
            field=models.IntegerField(null=True),
        ),
    ]
