# Generated by Django 2.0.2 on 2018-04-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSite', '0010_auto_20180426_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
